apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"catalog-postgresql"}]'
  labels:
    app: catalog-coolstore
    app.openshift.io/runtime: spring-boot
  name: catalog-coolstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-coolstore
  strategy: {}
  template:
    metadata:
      labels:
        app: catalog-coolstore
    spec:
      containers:
      - image: quay.io/mostmark/catalog-coolstore:latest
        name: catalog-coolstore