apiVersion: v1
kind: Secret
metadata:
  name: inventory-mariadb
type: Opaque
stringData:
  database-name: inventorydb
  database-password: inventory
  database-root-password: inventoryadmin
  database-user: inventory