apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"inventory-mariadb"}]'
  labels:
    app: inventory-coolstore
    app.openshift.io/runtime: quarkus
  name: inventory-coolstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-coolstore
  strategy: {}
  template:
    metadata:
      labels:
        app: inventory-coolstore
    spec:
      containers:
      - image: quay.io/mostmark/inventory-coolstore:latest
        name: inventory-coolstore
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3